### ISSUE TITLE
Running multiple test function files

### ISSUE THREAD

**Issue by adnanmateenpk** [SC5/serverless-mocha-plugin#17]
When i try to run multiple test files at a time it uses the last function (alphabetical order) for all the functions instead of using their respective functions

**Comment by JasonZecutiv** [comment]
Having the same problem.  We're about to wire out project up with a Jenkins and this is a blocker for us.

**Comment by JasonZecutiv** [comment]
I created the missing and still had problems with running multiple tests.  I noticed that the new tests I created had an extra wrapper.init(mod) statement.  Once I added that to all of my existing tests I was able to run all tests and everything now passes!

**Comment by adnanmateenpk** [comment]
I have updated to 5.8 but i am still getting the same issue :|

**Comment by adnanmateenpk** [comment]
tests are running fine individually

**Comment by rafaljanicki** [comment]
Have you moved wrapper.init to before()?

**Comment by mpuittinen** [comment]
Hi! Did you create the tests that are failing with the latest module version or with a version prior to that. 
The fix for the issue is related to the creation of the the test files. wrapper.init() should be inside before() or in it(). i.e. the existing test cases would need to be fixed manually.

-Mikael

**Comment by adnanmateenpk** [comment]
yeah that was the fix thanks, the wrapper.init() was calling earlier thanks for all the help!!!
