### ISSUE TITLE
SLS invoke shows vars.populateService(...).then is not a function

### ISSUE THREAD

**Issue by NikolaNikushev** [SC5/serverless-mocha-plugin#71]
Version of the plugin: Latest, tried with locking to version 1.3.6

I just followed the installation procedure with the latest version but I get the following error: 

![image](https://user-images.githubusercontent.com/3421041/30639101-df0638ee-9dfd-11e7-90c7-4775e909f42c.png)

If I switch to 1.3.3 and 1.3.5 the error is not there.
I also follow this tutorial to setup the project. https://serverless.com/blog/tdd-serverless/ but had the same outcome.

**Comment by laardee** [comment]
@NikolaNikushev Hi, thanks for reporting this issue. We had to change the populateService execution at some point because it changed somehow in the Serverless framework. If it is possible, you could upgrade your serverless version to >= 1.13.2, any working version of serverless after that should work.

**Comment by NikolaNikushev** [comment]
@laardee, that indeed fixed it. Thank you very much. 
Updated my serverless to the newest one and reinstall the plugin and everything works fine.
